version: "2.1"
services:
    laravel_fpm82:
        build:
            context: .
            dockerfile: images/Dockerfile82
        image: aimeos-fpm-82
        container_name: aimeos-laravel-fpm-82
        volumes:
            - ./html:/var/www/html
            - ./scripts/install.sh:/opt/install.sh
            - ./shared:/shared
            # to use agent from dev folder uncomment following lines or to install from package, put it in shared folder and uncomment installation in install.sh script
            # - $PATH_TO_ELASTIC_REPO/prod/native/_build/linuxmusl-x86-64-release/extension/code/elastic_otel_php_82.so:/opt/elastic/elastic-otel-php/elastic_otel_php_82.so
            # - $PATH_TO_ELASTIC_REPO/prod/native/_build/linuxmusl-x86-64-release/extension/code/elastic_otel_php_82.debug:/opt/elastic/elastic-otel-php/elastic_otel_php_82.debug
            # - $PATH_TO_ELASTIC_REPO/prod/native/_build/linuxmusl-x86-64-release/loader/code/elastic_otel_php_loader.so:/opt/elastic/elastic-otel-php/elastic_otel_php_loader.so
            # - $PATH_TO_ELASTIC_REPO/prod/php:/opt/elastic/elastic-otel-php/php
            # - ./cfg/99-elastic.ini:/usr/local/etc/php/conf.d/99-elastic.ini
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret-pw}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-laravel82}
            - OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS:-Authorization=<key>}
            - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-https://your endpoint}
            - OTEL_RESOURCE_ATTRIBUTES=service.name=aimeos-shop-fpm,service.version=1.2,deployment.environment=test
            - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
            - ELASTIC_OTEL_LOG_LEVEL_STDERR=debug
        links:
            - aimeos-fpm-mysql:mysql
        depends_on:
            - aimeos-fpm-mysql
        entrypoint: ash /opt/install.sh
        privileged: true
    aimeos-fpm-nginx:
        image: nginx:latest
        container_name: aimeos-nginx
        ports:
          - "8182:80"
        volumes:
          - ./html:/var/www/html
          - ./cfg/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel_fpm82
    aimeos-fpm-mysql:
        image: mysql:5.7
        volumes:
          - ./initdb:/docker-entrypoint-initdb.d
        ports:
           - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-secret-pw}
        container_name: aimeos-fpm-mysql
        command: mysqld --sql-mode=""
